files:
    include: 'front/scss/**/*.scss'
rules:
    extends-before-mixins: 2
    extends-before-declarations: 2
    placeholder-in-extend: 2
    mixins-before-declarations:
        - 2
        -
            exclude:
                - breakpoint
                - mq

    no-warn: 1
    no-debug: 1
    no-ids: 2
    no-important: 2

    indentation:
        - 4
        -
            size: 4

    variable-for-property:
        - 1
        -
            'properties':
            - 'margin'
            - 'content'
